"""Write data.js for the showreel from the demo event log.

Every number in the video, and every particle, comes from the real analysis of
examples/beanline_eventlog.csv: one dot per event, one count per node.

    python docs/showreel/make_data.py
"""
import csv
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from xray.analyze import analyze, load_event_log  # noqa: E402
from xray.eventlog import ACTIVITY_ORDER, ORDER_CONFIRMED  # noqa: E402
from xray.report import findings  # noqa: E402

EVENT_LOG = ROOT / "examples" / "beanline_eventlog.csv"
AS_OF = datetime(2026, 8, 31, 21, 0, tzinfo=timezone.utc)


def main():
    results = analyze(load_event_log(EVENT_LOG), company="Beanline Trading", as_of=AS_OF)

    rows = list(csv.DictReader(EVENT_LOG.open(encoding="utf-8")))
    orders = sorted({r["case_id"] for r in rows})
    order_index = {o: i for i, o in enumerate(orders)}
    people = sorted({r["resource"] for r in rows if r["resource"]})
    started = {}
    for r in rows:
        ts = datetime.fromisoformat(r["timestamp"])
        started[r["case_id"]] = min(started.get(r["case_id"], ts), ts)

    # Chronological, like one endless chatter feed across the whole database.
    rows.sort(key=lambda r: (r["timestamp"], r["case_id"], ACTIVITY_ORDER.index(r["activity"])))
    seen, events = set(), []
    for r in rows:
        ts = datetime.fromisoformat(r["timestamp"])
        first = (r["case_id"], r["activity"]) not in seen
        seen.add((r["case_id"], r["activity"]))
        extra = ""
        if r["detail"].startswith("amount"):
            old, new = r["detail"].split()[1::2]
            extra = f"€ {old}|€ {new}"
        elif r["detail"].startswith("+"):
            old = ts + timedelta(days=1)
            new = old + timedelta(days=float(r["detail"].split()[0]))
            extra = f"{old:%b %d}|{new:%b %d}"
        events.append([
            order_index[r["case_id"]],
            ACTIVITY_ORDER.index(r["activity"]),
            round((ts - started[r["case_id"]]).total_seconds() / 86400, 3),
            int(first),
            people.index(r["resource"]) if r["resource"] else -1,
            r["document"],
            f"{ts:%b %d · %H:%M}",
            extra,
        ])

    confirmed = {c.case_id for c in results.cases if c.has(ORDER_CONFIRMED)}
    problem_orders = {c.case_id for r in results.rules for c in r.hits}
    rules = {r.rule.key: r for r in results.rules}

    def finding(key):
        r = rules[key]
        c = r.concentration[0]
        return {"hits": len(r.hits), "applicable": r.applicable, "rate": round(r.rate, 3),
                "dimension": c.dimension, "values": c.values, "share": round(c.hit_share, 3),
                "groupRate": round(c.rate, 3), "fix": r.rule.odoo_fix}

    bottleneck = results.bottlenecks[0]
    data = {
        "company": results.company,
        "stats": {
            "orders": results.counts["quotations"],
            "events": results.counts["events"],
            "confirmed": results.counts["confirmed"],
            "conversion": round(results.counts["conversion"], 3),
            "orderToCashDays": round(results.order_to_cash.median_days, 1),
            "problemShare": round(len(problem_orders & confirmed) / len(confirmed), 3),
            "problemOrders": len(problem_orders),
            "problemKinds": len(findings(results)),
            "variants": results.counts["variants"],
        },
        "activities": ACTIVITY_ORDER,
        "people": people,
        "nodes": results.nodes,
        "edges": [[a, b, v["count"], None if v["median_days"] is None else round(v["median_days"], 2)]
                  for (a, b), v in results.edges.items() if a != "Start" and b != "End"],
        "findings": {
            "changed": finding("changed_after_confirmation"),
            "invoicedEarly": finding("invoiced_before_shipping"),
            "paidLate": finding("paid_late"),
            "rescheduled": finding("rescheduled_repeatedly"),
            "bottleneck": {"warehouse": bottleneck["warehouse"],
                           "typical": round(bottleneck["typical_days"], 1),
                           "slow": [[d, round(v, 1), n] for d, v, n in bottleneck["slow_days"]]},
        },
        "events": events,
    }
    out = Path(__file__).with_name("data.js")
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    out.write_text("// Generated by make_data.py from examples/beanline_eventlog.csv. Do not edit.\n"
                   f"window.XRAY_DATA = {body};\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}: {len(events)} events, {len(orders)} orders")


if __name__ == "__main__":
    main()
